version: '3'

services:
  app:
    container_name: vendor_app_api
    image: vendor-app-api-service:1.0.0
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        NODE_ENV: development
    command: npm run start:dev
    ports:
      - 3000:3000
      - 50051:50051
    env_file:
      - .env
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app

networks:
  nestjs-network:
    driver: bridge